---
title: "README"
author: "David Hugh-Jones"
date: "8 September 2015"
output: html_document
---

```{r, echo = FALSE, eval = FALSE}
# to create the markdown
render("README.Rmd", md_document(fig_width = 4, fig_height = 3))
```
# ffplot

`ffplot` is the fast, friendly plotting command for R. 

## Install

```{r, eval = FALSE}
library(devtools)
install_github("hughjonesd/ffplot")
```


## Examples

```{r}
library(ffplot)
library(ggplot2)
data(diamonds)
d30 <- diamonds[1:30,]
head(d30)
```


Simple scatterplots: 

```{r}
ffplot(price ~ carat, d30)
```

Plot numeric data by categories: 

```{r}
ffplot(price ~ color, d30)
```

Barplot of categories:

```{r}
ffplot(cut ~ color, d30)
```

Plot a function of your data:

```{r}
ffplot(range(price) ~ color, d30)
```

`ffplot` tries to guess what you want:

```{r}
ffplot(ci(price, 0.95) ~ color, d30)
```


Plot data with summary statistics:

```{r}
ffplot(price + mean(price) ~ color, d30)
```

Use any functions:

```{r}
ffplot(mean(price) + ci(price, .99) ~ color, d30, geom = c("point", "linerange"))
```

Change the defaults:

```{r}
ffplot(price ~ color, diamonds, geom ="violin")

```

```{r}
ffplot(mean(price) ~ color, diamonds, geom = "point", shape = 3)
```

Add `ggplot2` options:

```{r}
ffplot(cut ~ color, diamonds) + scale_fill_grey()
```
